package com.anand.backend.entity;

import com.anand.backend.enums.Genre;
import lombok.*;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.Instant;

/**
 * Represents a Movie document stored in the MongoDB <b>movie</b> collection.
 * <p>
 * This entity encapsulates all key metadata related to a video file uploaded and processed
 * by the system — including its descriptive details, file storage path, and size.
 * </p>
 *
 * <p>Annotations used:
 * <ul>
 *     <li>{@link Document} – Maps this class to the MongoDB collection.</li>
 *     <li>{@link Id} – Marks the primary key field used by MongoDB.</li>
 *     <li>{@link Data}, {@link Builder}, {@link AllArgsConstructor}, {@link NoArgsConstructor}, {@link ToString} – Lombok annotations to auto-generate boilerplate code.</li>
 * </ul>
 * </p>
 *
 * <p><b>Example JSON Representation:</b></p>
 * <pre>
 * {
 *   "movieId": "64fe39b32f9f7a18c01f8d2b",
 *   "movieTitle": "Inception",
 *   "movieDescription": "A thief who steals corporate secrets through dream-sharing technology.",
 *   "movieLength": "2h 28m",
 *   "IMDBRating": "8.8",
 *   "genre": "Sci-Fi",
 *   "filePath": "/videos/processed/inception/index.m3u8",
 *   "thumbnail": "/images/thumbnails/inception.jpg",
 *   "size": 1073741824
 * }
 * </pre>
 *
 * @author Krishanu
 * @since 2025
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@ToString
@Builder
@Document(collection = "movies")
public class Movie {
    /**
     * Unique identifier for the movie document.
     * Auto-generated by MongoDB upon insertion.
     */
    @Id
    private String movieId;

    private String movieTitle;
    private String movieDescription;
    private String movieLength;
    private String IMDBRating;
    private Genre genre;
    private String language;

    private String uploadedBy;
    private Instant uploadedAt = Instant.now();
    private int views = 0;
    private int likes = 0;

    @Builder.Default
    private int favoritesCount = 0;

    private String filePath;
    private String thumbnail;
    private long size;
}
