apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-service
  namespace: movie-platform
  labels:
    app: ml-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-service
  template:
    metadata:
      labels:
        app: ml-service
    spec:
      containers:
      - name: ml-service
        image: movie-streaming-platform-ml-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MONGO_URI
        - name: MONGO_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MONGO_DB_NAME
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MONGODB_URI
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: ml-service
  namespace: movie-platform
spec:
  selector:
    app: ml-service
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP
