package com.anand.backend.dto;

/**
 * Data Transfer Object (DTO) representing the outcome of the video processing pipeline.
 * <p>
 * This record encapsulates the file paths and metadata generated by the FFmpeg processing service,
 * including the HLS master playlist, generated thumbnails, preview GIFs, and video duration.
 * It is used to pass this information from the asynchronous processing service back to the main application logic.
 * </p>
 *
 * @param masterPlaylistFilename    The filename of the generated HLS master playlist (.m3u8).
 * @param thumbnailFilename         The filename of the static thumbnail image.
 * @param previewGifFilename        The filename of the animated preview GIF.
 * @param timelineThumbnailsPattern The filename pattern for timeline thumbnails (e.g., "thumb_%04d.jpg").
 * @param durationSeconds           The total duration of the processed video in seconds.
 */
public record VideoProcessingResult(
        String masterPlaylistFilename,
        String thumbnailFilename,
        String previewGifFilename,
        String timelineThumbnailsPattern,
        Integer durationSeconds
) {}